//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOP2V10
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParkingDbEntities : DbContext
    {
        public ParkingDbEntities()
            : base("name=ParkingDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cenovnik> Cenovniks { get; set; }
        public virtual DbSet<parking> parkings { get; set; }
        public virtual DbSet<Vlasnik> Vlasniks { get; set; }
    }
}
